apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-host
          image: asbis92/k8s-jenkins:%IMAGE-PLACEHOLDER%
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-svc
  labels:
    app: php-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
      protocol: TCP
  selector:
    app: php-app